[package]
name = "distinst_macros"
version = "0.3.2"
description = "Distribution Installer Backend -- Macros"
repository = "https://github.com/pop-os/distinst"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
license = "LGPL-3.0"

[dependencies]
